[package]
name = "libc-fuzzer"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
which = "4.2.5"
cc = "*"

[dependencies]
libafl = { version = "0.7.1", features = [
    "std",
    "derive",
    "introspection",
    "fork",
] }
tree-sitter = "0.20.6"
sexp = "1.1.4"
